const zh = {
 title: "活动", intro: "收录活动日程、挑战曲、积分奖励与限定故事。", stories: "活动故事", storyIntro: "活动里的相遇与日常，按章节慢慢读下去。",
 back: "全部活动", storyBack: "全部活动故事", allStories: "乐队主线", details: "查看活动", chapters: "章节目录", read: "阅读故事", unread: "正文待收录",
 events: "个活动", episodes: "话故事", milestones: "档积分奖励", songs: "首挑战曲", noEvents: "暂无活动资料", empty: "当前服务器版本尚未收录活动，后续资料将在这里展示。",
 noStories: "暂无活动故事", emptyStories: "当前服务器版本尚未收录活动章节。你可以先阅读其他剧情。", search: "搜索活动名称", clear: "清除搜索", noResults: "没有匹配的活动", dates: "活动时间", start: "开始", end: "结束", displayEnd: "展示截止",
 main: "活动正篇", another: "Another 故事", extra: "额外故事", points: "解锁积分", episode: "第", episodeEnd: "话", available: "话可读", collection: "浏览故事目录", about: "活动详情", original: "保留日文原文", sourceTime: "时间按游戏资料原样显示。", challenge: "挑战演出", event: "活动", jp: "日服", global: "国际服"
};
type Copy = Record<keyof typeof zh, string>;
const en: Copy = {
 title: "Events", intro: "Schedules, challenge songs, milestone rewards and event stories.", stories: "Event stories", storyIntro: "Explore the moments and encounters behind each event.",
 back: "All events", storyBack: "All event stories", allStories: "Story directory", details: "View event", chapters: "Chapters", read: "Read story", unread: "Text coming later",
 events: "events", episodes: "episodes", milestones: "milestones", songs: "challenge songs", noEvents: "No events yet", empty: "Events have not been archived for this server release yet.",
 noStories: "No event stories yet", emptyStories: "Event chapters are not available for this release. Explore other stories in the meantime.", search: "Search event titles", clear: "Clear search", noResults: "No matching events", dates: "Event schedule", start: "Starts", end: "Ends", displayEnd: "Display ends",
 main: "Main story", another: "Another story", extra: "Extra story", points: "Required points", episode: "Episode ", episodeEnd: "", available: "readable", collection: "Browse chapters", about: "Event details", original: "Original Japanese text", sourceTime: "Times are shown as recorded in the game data.", challenge: "Challenge live", event: "Event", jp: "Japan", global: "Global"
};
const tw: Copy = { ...zh, title: "活動", intro: "收錄活動日程、挑戰曲、積分獎勵與限定故事。", stories: "活動故事", storyIntro: "活動裡的相遇與日常，按章節慢慢讀下去。", back: "全部活動", storyBack: "全部活動故事", allStories: "劇情總覽", details: "查看活動", chapters: "章節目錄", read: "閱讀故事", unread: "正文待收錄", events: "個活動", episodes: "話故事", milestones: "檔積分獎勵", songs: "首挑戰曲", noEvents: "暫無活動資料", empty: "目前伺服器版本尚未收錄活動，後續資料將在這裡展示。", noStories: "暫無活動故事", emptyStories: "目前伺服器版本尚未收錄活動章節，可以先閱讀其他劇情。", search: "搜尋活動名稱", clear: "清除搜尋", noResults: "沒有符合條件的活動", dates: "活動時間", start: "開始", end: "結束", points: "解鎖積分", collection: "瀏覽故事目錄", about: "活動詳情", sourceTime: "時間按遊戲資料原樣顯示。", challenge: "挑戰演出", event: "活動", global: "國際服" };
const ja: Copy = { ...en, title: "イベント", intro: "開催期間・チャレンジ楽曲・報酬・イベントストーリーをまとめてチェック。", stories: "イベントストーリー", storyIntro: "イベントで描かれる出会いと日常を、エピソード順に。", back: "イベント一覧", storyBack: "イベントストーリー一覧", allStories: "ストーリー一覧", details: "イベント詳細", chapters: "エピソード一覧", read: "読む", unread: "本文は未収録", events: "イベント", episodes: "話", milestones: "段階の報酬", songs: "曲", noEvents: "イベント未収録", empty: "このサーバーのバージョンにはイベント情報がまだありません。", noStories: "イベントストーリー未収録", emptyStories: "このバージョンにはイベントの章がまだありません。ほかのストーリーをご覧ください。", search: "イベント名で検索", clear: "検索をクリア", noResults: "該当するイベントはありません", dates: "開催期間", start: "開始", end: "終了", displayEnd: "表示終了", main: "イベント本編", another: "アナザーストーリー", extra: "追加ストーリー", points: "解放ポイント", episode: "第", episodeEnd: "話", available: "話を収録", collection: "エピソードを見る", about: "イベント詳細", original: "日本語原文", sourceTime: "時刻はゲームデータの表記に従っています。", challenge: "チャレンジライブ", event: "イベント", jp: "日本", global: "グローバル" };
export const eventCopy = (locale: string): Copy => ({ "zh-CN": zh, "zh-TW": tw, en, ja }[locale] ?? zh);
